# Generated by Django 4.2.7 on 2025-08-07 18:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarsDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seating_capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('images', models.JSONField(default=list, help_text='List of image URLs (max 5)')),
                ('extra_features', models.JSONField(default=list, help_text='List of extra features')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cars_detail',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=200)),
                ('package_category', models.CharField(choices=[('adventure', 'Adventure'), ('family', 'Family'), ('romantic', 'Romantic'), ('business', 'Business'), ('pilgrimage', 'Pilgrimage'), ('wildlife', 'Wildlife')], max_length=50)),
                ('duration', models.PositiveIntegerField(help_text='Duration in days')),
                ('location', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'package_details',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('cust_location', models.CharField(max_length=200)),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('image', models.URLField(blank=True, help_text='Happy face image URL', max_length=500, null=True)),
                ('message_review', models.TextField()),
                ('mail_authenticated_tag', models.BooleanField(default=False)),
                ('customer_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'review_detail',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('place_name', models.CharField(max_length=200)),
                ('detail_summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pkg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='booking_api.packagedetails')),
            ],
            options={
                'db_table': 'location_detail',
                'ordering': ['-created_at'],
            },
        ),
    ]
