# Generated by Django 4.2.7 on 2025-08-08 19:25

import booking_api.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('booking_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carsdetail',
            name='images',
        ),
        migrations.RemoveField(
            model_name='locationdetail',
            name='image',
        ),
        migrations.RemoveField(
            model_name='reviewdetail',
            name='image',
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=booking_api.models.review_image_upload_path)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='booking_api.reviewdetail')),
            ],
            options={
                'db_table': 'review_images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_type', models.CharField(choices=[('car', 'Car Image'), ('location', 'Location Image'), ('review', 'Review Image'), ('package', 'Package Image')], max_length=20)),
                ('entity_id', models.UUIDField(help_text='ID of the related entity')),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'generic_images',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['image_type', 'entity_id'], name='generic_ima_image_t_364dc9_idx')],
            },
        ),
        migrations.CreateModel(
            name='LocationImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=booking_api.models.location_image_upload_path)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary image for the location')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='booking_api.locationdetail')),
            ],
            options={
                'db_table': 'location_images',
                'ordering': ['order', '-created_at'],
                'unique_together': {('location', 'order')},
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=booking_api.models.car_image_upload_path)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary image for the car')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='booking_api.carsdetail')),
            ],
            options={
                'db_table': 'car_images',
                'ordering': ['order', '-created_at'],
                'unique_together': {('car', 'order')},
            },
        ),
    ]
