# Generated by Django 4.2.7 on 2025-08-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_api', '0002_remove_carsdetail_images_remove_locationdetail_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carimage',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Car Image', 'verbose_name_plural': 'Car Images'},
        ),
        migrations.AlterModelOptions(
            name='carsdetail',
            options={'ordering': ['-created_at'], 'verbose_name': 'Car Detail', 'verbose_name_plural': 'Car Details'},
        ),
        migrations.AddField(
            model_name='carsdetail',
            name='car_description',
            field=models.TextField(default='Default description', help_text='Detailed description of the car features and specifications', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carsdetail',
            name='car_name',
            field=models.CharField(default='Default name', help_text="Name/Model of the car (e.g., 'Toyota Innova', 'Maruti Swift')", max_length=100),
            preserve_default=False,
        ),
    ]
